server:
  port: 8085
spring:
  application:
    name: spring-cloud-user-server
  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name} #注册到consul的服务名字



