server:
  port: 8181
spring:
  autoconfigure:
    #exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
  application:
    name: spring-cloud-gateway
  cloud:
    #注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name} #注册到consul的服务名字
    #路由网关
    gateway:
      routes:
      - id: book
        #uri: http://localhost:9080         #写法一 单uri
        uri: lb://spring-cloud-book-server  #写法二 lb:类型,表示从微服务注册中心订阅服务并且进行服务的路由
        predicates:
        - Path=/bookTest  #匹配路径转发 当访问http://localhost:8181/bookTest便会转发到http://localhost:9080/bookTest
















