spring:
  profiles:
   # active: dev
   # active: dev-gateway-path
   # active: dev-gateway-before
   # active: dev-gateway-stripprefix #过滤器
   # active: dev-gateway-hystrix #熔断
     active: dev-gateway-ratelimit #限流