server:
  port: 8181
spring:
  autoconfigure:
    #exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
  application:
    name: spring-cloud-gateway
  cloud:
    #注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name} #注册到consul的服务名字
    #路由网关
    gateway:
      routes:
      - id: book
        uri: http://localhost:9080
        predicates:
        - Before=2020-08-01T00:00:00+08:00[Asia/Shanghai]  #匹配路径转发 当访问http://localhost:8181/bookTest便会转发到http://localhost:9080/bookTest
















