server:
  port: 8181
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name} #注册到consul的服务名字

feign:
  hystrix:
    enabled: true #开启feign熔断












