server:
  port: 8282
spring:
  autoconfigure:
    #exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
  application:
    name: spring-cloud-sleuth
  cloud:
    #注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name} #注册到consul的服务名字
  #链路追踪
  zipkin:
   base-url: http://localhost:9411
   locator:
    discovery:
      enabled: true #支持通过服务发现来定位host name


  sleuth:
    web:
      client:
        enabled: true #web开启sleuth功能
    sampler:
      probability: 1.0 #[0,1],可以设置为小数,当设置为1.0时就是链路数据100%收集到zipkin,当设置为0.1时,即10%概率收集链路数据















