server:
  port: 8080
spring:
  application:
    name: spring-cloud-start
  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name} #注册到consul的服务名字

feign:
  hystrix:
    enabled: true #开启feign熔断


#turbine:
  #app-config: spring-cloud-book-server,spring-cloud-start #需要监控的服务
  #aggregator:
    #cluster-config: default
  #cluster-name-expression: new String("default")











