server:
  port: 8080
spring:
  application:
    name: spring-cloud-start
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name} #注册到consul的服务名字

feign:
  hystrix:
    enabled: true #开启feign熔断



