server:
  port: 8080
spring:
  application:
    name: spring-boot-mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.31:3306/search?useUnicode=true&ch4aracterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
   # url: jdbc:mysql://192.168.1.31:3306/search_2.2?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&allowMultiQueries=true&failOverReadOnly=false
    username: root
    password: ysten123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: TUTORIAL-POOL
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1






