server:
  port: 8080
spring:
  application:
    name: spring-boot-mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jimmy_database
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: TUTORIAL-POOL
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1




mybatis:
  mapper-locations: classpath*:com.tutorial.repository.mapper/*.xml



